### ISSUE TITLE
x64 tools knob

### ISSUE THREAD

**Issue by henricj** [seanmiddleditch/gha-setup-vsdevenv#4]
VsDevCmd.bat sets the host tools to x86 by default.  With larger C++ projects--particularly with LTCG, it can sometimes be helpful to use the x64-hosted tools by passing "-host_arch=amd64" to VsDevCmd.bat.

There are other useful options for things like specifying the Windows SDK version, the platform, and the toolset. 

For non-interactive use, "-startdir" should almost always be set to "none".

**Comment by seanmiddleditch** [comment]
I added `toolset_version`, `winsdk`, and `host_arch`.
